logger:
  level: debug
  encoding: json
  outputPaths:
    - stdout
  encoderConfig:
    messageKey: message
    levelKey: level
    levelEncoder: lowercase

database:
  host:   localhost
  port:   5432
  user:   default_user
  pass:   1
  dbname: catalog
